name: Build and Release

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get dependencies
      run: go mod download

    - name: Build binaries
      run: |
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -o webp2mp4-linux-amd64 main.go

        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o webp2mp4-linux-arm64 main.go

    - name: Generate version tag
      id: tag
      run: echo "tag=v$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: Release ${{ steps.tag.outputs.tag }}
        body: |
          Automated release from master branch

          ### Installation
          1. Download the appropriate binary for your system
          2. Make it executable: `chmod +x webp2mp4-*`
          3. Ensure ffmpeg is installed on your system
          4. Optional: Install ImageMagick for better compatibility
        files: |
          webp2mp4-linux-amd64
          webp2mp4-linux-arm64
        draft: false
        prerelease: false